apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      storage: data
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
        storage: data
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 256Mi
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 172.27.109.193
            - name: NFS_PATH
              value: /volume1/NFS
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.27.109.193
            path: /volume1/NFS
